const controllers = require('../controllers/students');
module.exports = [
  {
    method:'GET',
    path:'/groups',
    config:{
      auth:'jwt',
      handler:controllers.getGroups
    },
  },
  {
      method:'GET',
      path:'/group/{id}',
      config:controllers.getGroup
  },
  {
    method:'POST',
    path:'/groups/add',
    config:controllers.addGroup
  },{
    method:'POST',
    path:'/students/add',
    config:controllers.addStudentsToGroup
  },
  {
    method:'GET',
    path:'/student/{studentId}',
    config:controllers.getStudent
  },
  {
    method:'GET',
    path:'/group/info/{grpId}',
    config:controllers.getGroupStat
  },
    {
    method:'GET',
    path:'/student/{studentId}/info',
    config:controllers.getStudentSessionsInfo
  },
];

